[HorizonEngine.Rendering.RenderBackend]
RenderBackendType = "D3D12"
EnableValidationLayers = false
EnableHardwareRayTracing = false

[HorizonEngine.Rendering.Renderer]
ShaderCompilerSkipOptimization = false
ShaderCompilerGenerateDebugInfo = false
ShaderCompilerWarningAreErrors = true