[HorizonEngine.Rendering.RenderBackend]
EnableValidationLayers = false
RenderBackendType = "D3D12"
EnableHardwareRayTracing = false

[HorizonEngine.Rendering.Renderer]
ShaderCompilerSkipOptimization = false
ShaderCompilerGenerateDebugInfo = false
ShaderCompilerWarningAreErrors = true