project "HorizonEditorLauncher"
    --kind "WindowedApp"
    kind "ConsoleApp"
    entrypoint "mainCRTStartup"
    language "C++"
    cppdialect "C++latest"
    staticruntime "Off"
    location "%{wks.location}/Build/%{prj.name}"
    targetdir "%{wks.location}/Build/Bin/%{cfg.buildcfg}"
    debugdir "%{cfg.targetdir}"
    scanformoduledependencies "true"

    files {
        "**.h",
        "**.c",
        "**.hpp",
        "**.cpp",
        "**.cppm",
        "**.lua",
    }

    includedirs {
        enginepath("Source"),
        editorpath("Source"),
    }

    links {
        "HorizonEngine",
        "HorizonEditor",
        "imgui",
        --"USD",
        "RenderDoc",
        thirdpartypath("glfw/glfw-3.3.9.bin.WIN64/lib-vc2022/glfw3.lib"),
        thirdpartypath("dxc/dxc_2024_07_31/lib/x64/dxcompiler.lib"),
        thirdpartypath("optick/Optick_1.4.0/lib/x64/release/OptickCore.lib"),
        thirdpartypath("python/310/libs/python310.lib"),
        thirdpartypath("streamline/Streamline-2.4.15/lib/x64/sl.interposer.lib"),
    }

    prebuildcommands {
        "{MKDIR} %{cfg.targetdir}/D3D12",
        "{MKDIR} %{cfg.targetdir}/python310",
    }

    postbuildcommands {
        "{COPY} %{wks.location}/ThirdParty/optick/Optick_1.4.0/lib/x64/release/OptickCore.dll %{cfg.targetdir}",

        "{COPY} %{wks.location}/ThirdParty/dxc/dxc_2024_07_31/bin/x64/dxcompiler.dll %{cfg.targetdir}",
        "{COPY} %{wks.location}/ThirdParty/dxc/dxc_2024_07_31/bin/x64/dxil.dll %{cfg.targetdir}",

        "{COPY} %{wks.location}/ThirdParty/D3D12SDK/bin/x64/D3D12Core.dll %{cfg.targetdir}/D3D12",
        "{COPY} %{wks.location}/ThirdParty/D3D12SDK/bin/x64/d3d12SDKLayers.dll %{cfg.targetdir}/D3D12",
    }

    includedirs {
        enginepath("Source"),
        editorpath("Source"),
        thirdpartypath("entt/include"),
        thirdpartypath("dxc/dxc_2024_07_31/inc"),
        thirdpartypath("glfw/glfw-3.3.9.bin.WIN64/include"),
        thirdpartypath("glm/include"),
        thirdpartypath("spdlog/include"),
        thirdpartypath("mpmc/include"),
        thirdpartypath("imgui/imgui-1.89.9-docking"),
        thirdpartypath("stb/include"),
        thirdpartypath("physx/include"),
        thirdpartypath("optick/Optick_1.4.0/include"),
        thirdpartypath("vulkan/1.4.304.0/Include"),
        thirdpartypath("python/310/include"),
        thirdpartypath("miniaudio/include"),
    }

    postbuildcommands {
        "{COPYFILE} %{wks.location}/Source/HorizonEngine/Source/Rendering/Renderer/RasterizationRenderer/PerFrameShaderParameters.h %{wks.location}/Source/HorizonEngine/Shaders/RasterizationRenderer",
    }

    filter "configurations:Debug"
        links {
            thirdpartypath("physx/lib/debug/PhysX_64.lib"),
            thirdpartypath("physx/lib/debug/PhysXCommon_64.lib"),
            thirdpartypath("physx/lib/debug/PhysXFoundation_64.lib"),
            thirdpartypath("physx/lib/debug/PhysXExtensions_static_64.lib"),
            thirdpartypath("physx/lib/debug/PhysXPvdSDK_static_64.lib"),
            thirdpartypath("physx/lib/debug/PhysXVehicle_static_64.lib"),
            thirdpartypath("physx/lib/debug/PhysXVehicle2_static_64.lib"),
            thirdpartypath("physx/lib/debug/PhysXCharacterKinematic_static_64.lib"),
            thirdpartypath("physx/lib/debug/PhysXCooking_64.lib"),
            thirdpartypath("physx/lib/debug/PVDRuntime_64.lib"),
            thirdpartypath("physx/lib/debug/SceneQuery_static_64.lib"),

            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/tbb_debug.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/tbb12_debug.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/tbbmalloc_debug.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/tbbmalloc_proxy_debug.lib"),

            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/MaterialXCore.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/MaterialXFormat.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/MaterialXGenGlsl.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/MaterialXGenMdl.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/MaterialXGenMsl.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/MaterialXGenOsl.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/MaterialXGenShader.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/MaterialXRender.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/MaterialXRenderGlsl.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/MaterialXRenderHw.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/MaterialXRenderOsl.lib"),

            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/osdCPU.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/osdGPU.lib"),

            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_ar.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_arch.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_boost.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_cameraUtil.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_garch.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_geomUtil.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_gf.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_glf.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hd.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hdar.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hdGp.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hdMtlx.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hdSt.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hdx.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hf.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hgi.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hgiGL.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hgiInterop.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hio.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_js.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_kind.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_ndr.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_pcp.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_pegtl.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_plug.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_pxOsd.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_python.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_sdf.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_sdr.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_tf.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_trace.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_ts.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usd.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdAppUtils.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdBakeMtlx.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdGeom.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdGeomValidators.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdHydra.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdImaging.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdImagingGL.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdLux.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdMedia.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdMtlx.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdPhysics.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdPhysicsValidators.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdProc.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdProcImaging.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdRender.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdRi.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdRiPxrImaging.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdSemantics.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdShade.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdShadeValidators.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdSkel.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdSkelImaging.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdSkelValidators.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdUI.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdUtils.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdUtilsValidators.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdValidation.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdviewq.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdVol.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdVolImaging.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_vt.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/debug/usd_work.lib"),

            thirdpartypath("python/310/libs/python310.lib"),

            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_backend_dx12_x64d.lib"),
            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_backend_vk_x64d.lib"),
            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_fsr2_x64d.lib"),
            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_opticalflow_x64d.lib"),
            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_fsr3_x64d.lib"),
            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_fsr3upscaler_x64d.lib"),
            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_frameinterpolation_x64d.lib"),

            thirdpartypath("metis/metis-5.1.0/libmetis/Debug/metis.lib"),
        }
        postbuildcommands {
            "{COPY} %{wks.location}/ThirdParty/physx/lib/debug/PhysX_64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/physx/lib/debug/PhysXFoundation_64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/physx/lib/debug/PhysXCommon_64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/physx/lib/debug/PhysXCooking_64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/physx/lib/debug/PVDRuntime_64.dll %{cfg.targetdir}",

            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/tbb12_debug.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/tbbmalloc_debug.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/tbbmalloc_proxy_debug.dll %{cfg.targetdir}",

            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/MaterialXCore.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/MaterialXFormat.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/MaterialXGenGlsl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/MaterialXGenMdl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/MaterialXGenMsl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/MaterialXGenOsl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/MaterialXGenShader.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/MaterialXRender.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/MaterialXRenderGlsl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/MaterialXRenderHw.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/debug/MaterialXRenderOsl.dll %{cfg.targetdir}",

            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd %{cfg.targetdir}/usd",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_ar.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_arch.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_boost.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_cameraUtil.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_garch.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_geomUtil.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_gf.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_glf.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hd.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hdar.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hdGp.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hdMtlx.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hdsi.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hdSt.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hdx.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hf.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hgi.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hgiGL.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hgiInterop.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_hio.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_js.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_kind.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_ndr.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_pcp.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_pegtl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_plug.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_pxOsd.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_python.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_sdf.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_sdr.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_tf.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_trace.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_ts.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usd.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdAppUtils.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdBakeMtlx.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdGeom.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdGeomValidators.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdHydra.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdImaging.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdImagingGL.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdLux.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdMedia.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdMtlx.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdPhysics.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdPhysicsValidators.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdProc.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdProcImaging.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdRender.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdRi.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdRiPxrImaging.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdSemantics.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdShade.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdShadeValidators.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdSkel.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdSkelImaging.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdSkelValidators.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdUI.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdUtils.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdUtilsValidators.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdValidation.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdviewq.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdVol.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_usdVolImaging.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_vt.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/debug/usd_work.dll %{cfg.targetdir}",

            "{COPY} %{wks.location}/ThirdParty/python/310/bin/python3.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/python/310/bin/python310.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/python/310/bin %{cfg.targetdir}/python310/bin",
            "{COPY} %{wks.location}/ThirdParty/python/310/lib %{cfg.targetdir}/python310/lib",
            "{COPY} %{wks.location}/ThirdParty/python/310/DLLs %{cfg.targetdir}/python310/DLLs",

            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_backend_dx12_x64d.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_backend_vk_x64d.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_fsr2_x64d.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_opticalflow_x64d.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_fsr3_x64d.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_fsr3upscaler_x64d.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_frameinterpolation_x64d.dll %{cfg.targetdir}",

            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/development/NvLowLatencyVk.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/development/nvngx_dlss.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/development/nvngx_dlssg.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/development/sl.common.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/development/sl.dlss.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/development/sl.dlss_g.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/development/sl.imgui.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/development/sl.interposer.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/development/sl.nvperf.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/development/sl.pcl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/development/sl.reflex.dll %{cfg.targetdir}",
        }

    filter "configurations:Test or Release"
        links {
            thirdpartypath("physx/lib/release/PhysX_64.lib"),
            thirdpartypath("physx/lib/release/PhysXCommon_64.lib"),
            thirdpartypath("physx/lib/release/PhysXFoundation_64.lib"),
            thirdpartypath("physx/lib/release/PhysXExtensions_static_64.lib"),
            thirdpartypath("physx/lib/release/PhysXPvdSDK_static_64.lib"),
            thirdpartypath("physx/lib/release/PhysXVehicle_static_64.lib"),
            thirdpartypath("physx/lib/release/PhysXVehicle2_static_64.lib"),
            thirdpartypath("physx/lib/release/PhysXCharacterKinematic_static_64.lib"),
            thirdpartypath("physx/lib/release/PhysXCooking_64.lib"),
            thirdpartypath("physx/lib/release/PVDRuntime_64.lib"),
            thirdpartypath("physx/lib/release/SceneQuery_static_64.lib"),


            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/tbb_debug.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/tbb12_debug.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/tbbmalloc_debug.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/tbbmalloc_proxy_debug.lib"),

            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/MaterialXCore.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/MaterialXFormat.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/MaterialXGenGlsl.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/MaterialXGenMdl.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/MaterialXGenMsl.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/MaterialXGenOsl.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/MaterialXGenShader.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/MaterialXRender.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/MaterialXRenderGlsl.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/MaterialXRenderHw.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/MaterialXRenderOsl.lib"),

            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/osdCPU.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/osdGPU.lib"),

            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_ar.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_arch.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_boost.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_cameraUtil.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_garch.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_geomUtil.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_gf.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_glf.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_hd.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_hdar.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_hdGp.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_hdMtlx.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_hdSt.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_hdx.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_hf.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_hgi.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_hgiGL.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_hgiInterop.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_hio.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_js.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_kind.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_ndr.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_pcp.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_pegtl.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_plug.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_pxOsd.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_python.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_sdf.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_sdr.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_tf.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_trace.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_ts.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usd.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdAppUtils.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdBakeMtlx.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdGeom.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdGeomValidators.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdHydra.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdImaging.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdImagingGL.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdLux.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdMedia.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdMtlx.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdPhysics.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdPhysicsValidators.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdProc.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdProcImaging.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdRender.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdRi.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdRiPxrImaging.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdSemantics.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdShade.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdShadeValidators.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdSkel.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdSkelImaging.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdSkelValidators.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdUI.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdUtils.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdUtilsValidators.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdValidation.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdviewq.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdVol.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdVolImaging.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_vt.lib"),
            thirdpartypath("OpenUSD/OpenUSD-25.05.01/lib/release/usd_work.lib"),

            thirdpartypath("python/310/libs/python310.lib"),

            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_backend_dx12_x64.lib"),
            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_backend_vk_x64.lib"),
            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_fsr2_x64.lib"),
            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_opticalflow_x64.lib"),
            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_fsr3_x64.lib"),
            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_fsr3upscaler_x64.lib"),
            thirdpartypath("FidelityFX/sdk/bin/ffx_sdk/ffx_frameinterpolation_x64.lib"),

            thirdpartypath("metis/metis-5.1.0/libmetis/Release/metis.lib"),
        }
        postbuildcommands {
            "{COPY} %{wks.location}/ThirdParty/physx/lib/release/PhysX_64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/physx/lib/release/PhysXFoundation_64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/physx/lib/release/PhysXCommon_64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/physx/lib/release/PhysXCooking_64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/physx/lib/release/PVDRuntime_64.dll %{cfg.targetdir}",

            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/tbb12_debug.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/tbbmalloc_debug.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/tbbmalloc_proxy_debug.dll %{cfg.targetdir}",

            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/MaterialXCore.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/MaterialXFormat.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/MaterialXGenGlsl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/MaterialXGenMdl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/MaterialXGenMsl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/MaterialXGenOsl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/MaterialXGenShader.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/MaterialXRender.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/MaterialXRenderGlsl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/MaterialXRenderHw.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/bin/release/MaterialXRenderOsl.dll %{cfg.targetdir}",

            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd %{cfg.targetdir}/usd",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_ar.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_arch.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_boost.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_cameraUtil.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_garch.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_geomUtil.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_gf.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_glf.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_hd.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_hdar.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_hdGp.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_hdMtlx.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_hdsi.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_hdSt.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_hdx.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_hf.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_hgi.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_hgiGL.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_hgiInterop.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_hio.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_js.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_kind.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_ndr.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_pcp.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_pegtl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_plug.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_pxOsd.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_python.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_sdf.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_sdr.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_tf.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_trace.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_ts.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usd.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdAppUtils.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdBakeMtlx.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdGeom.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdGeomValidators.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdHydra.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdImaging.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdImagingGL.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdLux.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdMedia.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdMtlx.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdPhysics.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdPhysicsValidators.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdProc.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdProcImaging.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdRender.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdRi.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdRiPxrImaging.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdSemantics.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdShade.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdShadeValidators.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdSkel.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdSkelImaging.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdSkelValidators.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdUI.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdUtils.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdUtilsValidators.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdValidation.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdviewq.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdVol.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_usdVolImaging.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_vt.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/OpenUSD/OpenUSD-25.05.01/lib/release/usd_work.dll %{cfg.targetdir}",

            "{COPY} %{wks.location}/ThirdParty/python/310/bin/python3.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/python/310/bin/python310.dll %{cfg.targetdir}",

            "{COPY} %{wks.location}/ThirdParty/python/310/bin %{cfg.targetdir}/python310/bin",
            "{COPY} %{wks.location}/ThirdParty/python/310/lib %{cfg.targetdir}/python310/lib",
            "{COPY} %{wks.location}/ThirdParty/python/310/DLLs %{cfg.targetdir}/python310/DLLs",

            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_backend_dx12_x64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_backend_vk_x64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_fsr2_x64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_opticalflow_x64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_fsr3_x64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_fsr3upscaler_x64.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/FidelityFX/sdk/bin/ffx_sdk/ffx_frameinterpolation_x64.dll %{cfg.targetdir}",

            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/NvLowLatencyVk.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/nvngx_dlss.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/nvngx_dlssg.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/sl.common.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/sl.dlss.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/sl.dlss_g.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/sl.interposer.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/sl.pcl.dll %{cfg.targetdir}",
            "{COPY} %{wks.location}/ThirdParty/streamline/Streamline-2.4.15/bin/x64/sl.reflex.dll %{cfg.targetdir}",
        }
