#pragma once

#define D3D12_RENDER_BACKEND_BINDLESS_MAX_NUM_RESOURCE_DESCRIPTOERS (16 * 1024)
#define D3D12_RENDER_BACKEND_BINDLESS_MAX_NUM_SAMPLER_DESCRIPTOERS (256)

#define D3D12_RENDER_BACKEND_USE_RENDER_PASS 1
